-- Up
CREATE TABLE products( id INT, 
    name TEXT NOT NULL, 
    price INT NOT NULL, 
    imgSrc TEXT NOT NULL, 
    itemType TEXT NOT NULL, 
    colour TEXT NOT NULL, 
    stock INT NOT NULL
);

-- INSERT INTO products (id, itemName, price, imgSrc, itemType, colour, inCart, stock) VALUES ("0", 'Item0', "0.50", './images/brick0.jpg', 'brick', 'White', "0", "50");
INSERT INTO products(id, name, price, imgSrc, itemType, colour, stock) VALUES
    (0, 'Bonsai-Set', 50, './images/bonsai.jpg', 'set', 'Multi', 50), 
    (1, 'Bonsai-Leaf', 10, './images/bonsaiLeaf.jpg', 'set', 'Multi', 50), 
    (2, 'Tree-House-Set', 50, './images/treeSet.jpg', 'set', 'Multi', 50), 
    (3, 'Tree-Leaves', 10, './images/treeLeaves.jpg', 'set', 'Mutli', 50), 
    (4, 'Tulips', 12, './images/tulips.jpg', 'set', 'Mutli', 50), 
    (5, 'Plant', 12, './images/plant.jpg', 'set', 'Mutli', 50), 
    (6, 'Bouquet', 12, './images/bouquet.jpg', 'set', 'Mutli', 50), 
    (7, 'Flowers', 12, './images/flowers.jpg', 'set', 'Mutli', 50), 
    (8, 'Tokyo-Set', 50, './images/item7.jpg', 'set', 'Multi', 50), 
    (9, 'Singapore-Set', 50, './images/item8.jpg', 'set', 'Mutli', 7), 
    (10, 'New-York-Set', 50, './images/item9.jpg', 'set', 'Multi', 9), 
    (11, 'Paris-Set', 50, './images/item10.jpg', 'set', 'Multi', 50), 
    (12, 'London-Set', 50, './images/item11.jpg', 'set', 'Multi', 50), 
    (13, 'Taj-Mahal', 50, './images/item12.jpg', 'set', 'Multi', 50), 
    (14, 'Colosseum', 50, './images/item13.jpg', 'set', 'Multi', 50),
    (15, 'Owl-Set', 10, './images/item14.jpg', 'set', 'Multi', 50),
    (16, 'Dog-Set', 10, './images/item15.jpg', 'set', 'Multi', 50),
    (17, 'Tuktuk', 25, './images/item16.jpg', 'set', 'Multi', 50),
    (18, 'Taxi', 25, './images/item17.jpg', 'set', 'Multi', 50),
    (19, 'Brick-White-2x4', 1, './images/brick0.jpg', 'brick', 'White', 500),
    (20, 'Brick-Red-2x4', 1, './images/brick1.jpg', 'brick', 'Red', 500), 
    (21, 'Brick-Black-2x4', 1, './images/brick2.jpg', 'brick', 'Black', 500), 
    (22, 'Brick-Orange-2x4', 1, './images/brick3.jpg', 'brick', 'Orange', 500), 
    (23, 'Brick-Green-2x4', 1, './images/brick4.jpg', 'brick', 'Green', 500), 
    (24, 'Brick-Yellow-2x4', 1, './images/brick5.jpg', 'brick', 'Yellow', 500), 
    (25, 'Brick-Grey-2x4', 1, './images/brick6.jpg', 'brick', 'Grey', 0),
    (26, 'Brick-White-2x2', 1, './images/2x2brick1.jpg', 'brick', 'White', 500),
    (27, 'Brick-Red-2x2', 1, './images/2x2brick2.jpg', 'brick', 'Red', 500),
    (28, 'Brick-Orange-2x2', 1, './images/2x2brick3.jpg', 'brick', 'Orange', 500),
    (29, 'Brick-Green-2x2', 1, './images/2x2brick4.jpg', 'brick', 'Green', 500),
    (30, 'Brick-Blue-2x2', 1, './images/2x2brick5.jpg', 'brick', 'Blue', 500),
    (31, 'Roof-White', 1, './images/roof1.jpg', 'brick', 'White', 500),
    (32, 'Roof-Red', 1, './images/roof2.jpg', 'brick', 'Red', 500),
    (33, 'Roof-Black', 1, './images/roof3.jpg', 'brick', 'Black', 500),
    (34, 'Roof-Orange', 1, './images/roof4.jpg', 'brick', 'Orange', 500),
    (35, 'Plate-White-2x6', 1, './images/2x6plate1.jpg', 'brick', 'White', 500),
    (36, 'Plate-Red-2x6', 1, './images/2x6plate2.jpg', 'brick', 'Red', 500),
    (37, 'Plate-Blue-2x6', 1, './images/2x6plate3.jpg', 'brick', 'Blue', 500),
    (38, 'Plate-Yellow-2x6', 1, './images/2x6plate4.jpg', 'brick', 'Yellow', 500),
    (39, 'Plate-White-2x2', 1, './images/2x2plate1.jpg', 'brick', 'White', 500),
    (40, 'Plate-Red-2x2', 1, './images/2x2plate2.jpg', 'brick', 'Red', 500),
    (41, 'Plate-Yellow-2x2', 1, './images/2x2plate3.jpg', 'brick', 'Yellow', 500),
    (42, 'Plate-Black-2x2', 1, './images/2x2plate4.jpg', 'brick', 'Black', 500),
    (43, 'Plate-Blue-2x2', 1, './images/2x2plate5.jpg', 'brick', 'Blue', 500);
    

-- Down
DROP TABLE products;
